language: python

services:
- redis-server
- elasticsearch

cache: pip

python:
- '3.6'

install:
- make install

before_script:
- pip freeze
- sleep 10  # wait for es to come up
- curl -u elastic:changeme localhost:9200

script:
- make lint
- make test

after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)
