language: python

services:
- redis-server

cache: pip

addons:
  apt:
    packages:
    - oracle-java8-set-default

python:
- '3.6'

install:
- curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.deb
- sudo dpkg -i --force-confnew elasticsearch-5.4.0.deb
- "echo 'xpack.security.enabled: false' | sudo tee --append /etc/elasticsearch/elasticsearch.yml"
- sudo service elasticsearch start
- make install

before_script:
- pip freeze
- sleep 6  # wait for es to come up
- curl -v localhost:9200

script:
- make lint
- make test

after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)
