version: '2.1'
services:
  logs:
    ports:
    - 8001:80
    networks:
    - public

  nginx:
    image: nginx:1.13-alpine
    restart: always
    volumes:
    - ./nginx/dev.nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 8000:80
    depends_on:
    - web
    networks:
    - public
    - private
