version: '2.1'

services:
  logs:
    entrypoint:
    - '/bin/logspout'
    - '${LOGSPOUT_ENDPOINT}'
    ports:
    - 8001:80
    networks:
    - public

  nginx:
    image: morpheus-nginx
    restart: always
    ports:
    - 443:443
    depends_on:
    - web
    networks:
    - public
    - private
