version: '2.1'

services:
  logs:
    entrypoint:
    - '/bin/logspout'
    - '${LOGSPOUT_ENDPOINT}'
    ports:
    - 5001:80

  elastic:
    environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms7g -Xmx7g"
    ulimits:
      nproc: 3000
      nofile: 65536
      memlock: -1
    mem_limit: 10g

  nginx:
    image: morpheus-nginx
    restart: always
    ports:
    - 443:443
    depends_on:
    - web

  telegraf:
    image: telegraf:1.3-alpine
    hostname: morpheus-telegraf
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /var/run/utmp:/var/run/utmp:ro
    - /proc/net/:/proc/net/:ro
    environment:
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
    pid: host
    restart: always
    depends_on:
    - logs
    - elastic
    - redis
